### ISSUE TITLE
Credits got zeroed

### ISSUE THREAD

**Issue by abrandemuehl** [acm-uiuc/groot-credits-service#11]
I had 500 credits a few days ago (as per the default amount). Now I have zero. 

My guess is a service is down, since I also don't have a pin assigned.

**Comment by bcongdon** [comment]
I did some investigation and this is a bug with merch, not with credits.

**Comment by sameetandpotatoes** [comment]
After resolving https://github.com/acm-uiuc/groot-merch-service/issues/17, I noticed that the default credits still seems to be 5 for many people. Do we still need to do a migration?

**Comment by bcongdon** [comment]
It looks like the credits service fix never got deployed. I'll deploy and do a manual migration right now. Good catch.

**Comment by bcongdon** [comment]
Ah, the issue was that I didn't change the transaction amount, I only changed the user balance. The issue should be resolved now.
